### ISSUE TITLE
CohMetrix license

### ISSUE THREAD

**Issue by absolutwillie** [memphis-iis/cohmetrix-issues#103]
Name: Willie Knoetze

Email: knoetzef@coventry.ac.uk

Insitution: Coventry University

Registration page: 404 error
![image](https://github.com/user-attachments/assets/b1910bbf-3576-4d3c-94b0-6df583e4e2f9)

Description of your research: PhD research on the development of communicative meaning-making skills.

**Comment by absolutwillie** [comment]
I'm not sure what to enter, or how to obtain an API Key for 1.0.6. Please advise?

**Comment by JRustyHaner** [comment]
@absolutwillie Please try http://cohmetrix.memphis.edu/, we moved the website
