### ISSUE TITLE
Online portal isn't working 

### ISSUE THREAD

**Issue by cideri** [memphis-iis/cohmetrix-issues#106]
404 bad gateway

**Comment by JRustyHaner** [comment]
@cideri Thank you for reporting the outage, it has been restarted.

**Comment by cideri** [comment]
Thank you, unfortunately it still doesn’t work. 
The page doesn’t load.
Best, 
Camilla 
￼
__________________________

Camilla De Riso
Postdoctoral researcher 

Dept. of Humanities
Sect. of Theoretical and Applied Linguistics
University of Pavia
Piazza del Lino, 2
27100 - Pavia
Italy

**Comment by JRustyHaner** [comment]
![image](https://github.com/user-attachments/assets/a639ce58-0124-4c50-ab3f-f371a49ac05e)

Are you using the correct url: https://cohmetrix.memphis.edu?

**Comment by cideri** [comment]
Yes, this is the message popping up now
I’ve tried using my hotspot and not Pavia University Wi-Fi but the message is the same now.
I’m sorry for all the trouble, I’ve used the portal before and it was just fine!
Thanks again 

￼

__________________________

Camilla De Riso
Postdoctoral researcher 

Dept. of Humanities
Sect. of Theoretical and Applied Linguistics
University of Pavia
Piazza del Lino, 2
27100 - Pavia
Italy

**Comment by cideri** [comment]
No it’s not working now. 
Sorry for the confusion.
