### ISSUE TITLE
License Key Generation Failed 

### ISSUE THREAD

**Issue by cideri** [memphis-iis/cohmetrix-issues#107]
License key generation failed. Please check your username and API Key. Error: Error: License Server Unreachable: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
Please try again.

Downloaded latest version as requested when opening Windows Desktop version and now I can't access.

**Comment by JRustyHaner** [comment]
A 404 error indicates that the domain is unreachable to you. Please try to open a browser to http://cohmetrix.memphis.edu/api/getDesktopKey and verify that you get this message:

error: missing parameters, please provide email, apiKey, and secret

**Comment by cideri** [comment]
I get that message. What should I do?

**Comment by JRustyHaner** [comment]
@cideri I'm looking into this, if you need me to run a corpus when I have a minute, please email iisdevs@memphis.edu with your corpus.

**Comment by JRustyHaner** [comment]
@cideri Look for a fix tomorrow for this. We have changed API toolkits for license generation. The Linux version works now, but it will take a second for the Windows version.

**Comment by kuh-muh** [comment]
I get the same error as cideri, but when im opening the link http://cohmetrix.memphis.edu/api/getDesktopKey i get this message:  "status":"error","message":"API endpoint does not exist". I'm using windows 11

**Comment by JRustyHaner** [comment]
@kuh-muh @cideri 
Please download the new release.

**Comment by cideri** [comment]
I did and now it says that access to license.txt is denied. I've tried to look for the file as you suggested in previous issue but it does not exist in my folder.

**Comment by JRustyHaner** [comment]
@cideri please run as administrator
