### ISSUE TITLE
Can't Generate API Key Due To Cohmetrix Website Being Down

### ISSUE THREAD

**Issue by magiccactus221** [memphis-iis/cohmetrix-issues#111]
Howdy!

Following on from the issue I posted yesterday, (https://github.com/memphis-iis/cohmetrix-issues/issues/110) the Cohmetrix Core CLI build 9 I downloaded appeared to stabilize itself overnight. That said, I still cannot log in to the Cohmetrix web portal to get my API key (I am still getting 502 Bad Gateway errors every time I attempt to visit the web portal) (I'm registered and have an account already.) Is there any way to have the key generated and emailed to me? If so, please email me at martin.walczak@times.uh.edu, thanks!

**Comment by JRustyHaner** [comment]
@magiccactus221 Try again please, thanks for your patience.
