### ISSUE TITLE
Asking about License Key

### ISSUE THREAD

**Issue by muhilhamws** [memphis-iis/cohmetrix-issues#13]
Name: Muhammad Ilham Wahyu Saputro

Email: muhilhamwees@gmail.com

Institution: Sebelas Maret University

Secret key:

Description of your research: Analysis of Readability Level of Reading Texts on English Textbook

**Comment by JRustyHaner** [comment]
@muhilhamws I need a secret key from the first time you run CohMetrix to complete your request. I'd be happy to give you a key once I have that.

**Comment by muhilhamws** [comment]
@JRustyHaner Sorry i dont know what you mean, because this is my first time run CohMetrix. Is it 3 number at the beginning?

**Comment by JRustyHaner** [comment]
@muhilhamws That's it

**Comment by muhilhamws** [comment]
@JRustyHaner 706 sir, thank you
