### ISSUE TITLE
license key request

### ISSUE THREAD

**Issue by xiaohulugo** [memphis-iis/cohmetrix-issues#14]
Name: Ivy Wang

Email: wangheq2@msu.edu

Institution: Michigan State University

Secret key: 703

Description of your research: Analyze student data for my upcoming dissertation

**Comment by shilvmini** [comment]
Name: Iv Min

Email: lvmin221114@163.com

Institution: University of Shanghai for Science and Technology

Secret key: 710

Description of your research: Analyze lexcial complexity of academic papers
