### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by ljt2623** [memphis-iis/cohmetrix-issues#25]
when i input one text for testing, this erro occurs. 
![image](https://github.com/memphis-iis/cohmetrix-issues/assets/81426257/33069783-520d-4e0e-ac81-a1ec753587eb)

**Comment by seventeen-14** [comment]
Hi, I had the same problem. And when I selected an input file, there was no selective one. So, I didn't know whether should I select a file, txt or docx. I wondered whether a full processing procure could be provided by using whatever corpus. 
![screenshot 2024-01-03 165229](https://github.com/memphis-iis/cohmetrix-issues/assets/154567165/d29f2904-2557-46d8-be70-b944c9c28c15)
![screenshot 2024-01-03 165840](https://github.com/memphis-iis/cohmetrix-issues/assets/154567165/1dc8e6cf-71e6-4df1-8661-786a00b9209a)
And I have one more question: what's the "build" stand for? Now I use build 3, and is there anything wrong with it?

**Comment by JRustyHaner** [comment]
@ljt2623 you should direct cohmetrix to the folder containing txt files. If you have problems processing a corpus, please email it to jrhaner@memphis.edu

The build number is indicative of which version of the software you have.

**Comment by ljt2623** [comment]
@JRustyHaner Thanks for answering. I have directed to my input folder and set the output folder and error still occurred. 

> Started: 04beijing spring.txt Thread: 13
ERROR: -Popularte text- SentenceParserBridge
   at SentenceParserBridge.SPB.Run(String command, String args) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\SentenceParserBridge\SentenceParserBridge.cs:line 29
   at MPCharniak.Charniak.start() in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCharniak\Charniak.cs:line 96
   at MPCharniak.Charniak.parse(String sentence) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCharniak\Charniak.cs:line 137
   at MPCharniak.Charniak.parse2(String[] sentences) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCharniak\Charniak.cs:line 157
   at MPCharniak.MPParser.parse(String[] sentences) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCharniak\MPParser.cs:line 46
   at MPCohMetrix.CohMetrix.GetTextRep(String text) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\CohMetrix.cs:line 1138
   at MPCohMetrix.CohMetrix.AnalyzeTextForWeb(String text) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\CohMetrix.cs:line 188

**Comment by JRustyHaner** [comment]
@ljt2623 There are two possibilities here:

-The software failed to download the data files (located in your installation folder C:\Program Files(x86)\CohMetrixCore\data  

-Your corpus contains characters that are not compatible with CohMetrix.

**Comment by ljt2623** [comment]
@JRustyHaner 1. i have tried many texts but still failed same error 2. i checked the data it existed. 3. i I reinstalled the program and the problem persists. The following error message pops 

> System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path)
   at CohMetrix2023.Form1.button2_Click(Object sender, EventArgs e) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\CohMetrix2023\Form1.cs:line 330
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Private.CoreLib.dll
----------------------------------------
CohMetrixCore Desktop
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///C:/Program%20Files%20(x86)/CohMetrixCore/bin/CohMetrixCore%20Desktop.dll
----------------------------------------
System.Runtime
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    程序集版本:6.0.2.0
    Win32 版本:6.0.2523.51916
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.25/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:6.0.2.0
    Win32 版本:6.0.2523.51916
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.25/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Collections.dll
----------------------------------------
IISLicensing
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///C:/Program%20Files%20(x86)/CohMetrixCore/bin/IISLicensing.dll
----------------------------------------
IISUpdater
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    代码库:file:///C:/Program%20Files%20(x86)/CohMetrixCore/bin/IISUpdater.dll
----------------------------------------
System.Drawing.Common
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.25/System.Drawing.Common.dll
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Threading.Thread.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:6.0.2523.51916
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.25/Accessibility.dll
----------------------------------------
System.Numerics.Vectors
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.25/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Runtime.Loader
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:6.0.2.0
    Win32 版本:6.0.2523.51916
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.25/zh-Hans/System.Windows.Forms.resources.dll
----------------------------------------
System.ComponentModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.ComponentModel.dll
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Memory
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Memory.dll
----------------------------------------
System.Net.Http
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Net.Primitives.dll
----------------------------------------
System.Console
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Console.dll
----------------------------------------
System.Net.NetworkInformation
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Net.NetworkInformation.dll
----------------------------------------
System.Private.Uri
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Private.Uri.dll
----------------------------------------
System.Diagnostics.Tracing
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Collections.Concurrent
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Collections.Concurrent.dll
----------------------------------------
System.Net.Requests
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Net.Requests.dll
----------------------------------------
System.Net.WebClient
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Net.WebClient.dll
----------------------------------------
System.Net.WebHeaderCollection
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Net.WebHeaderCollection.dll
----------------------------------------
System.Net.ServicePoint
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Net.ServicePoint.dll
----------------------------------------
System.Collections.NonGeneric
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Collections.NonGeneric.dll
----------------------------------------
System.Net.Sockets
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Net.NameResolution.dll
----------------------------------------
System.Threading.ThreadPool
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Threading.ThreadPool.dll
----------------------------------------
System.Security.Cryptography.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Security.Principal.Windows
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Security.Claims.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Security.Cryptography.Encoding
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Text.Encoding.Extensions
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Text.Encoding.Extensions.dll
----------------------------------------
System.IO.Compression.ZipFile
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.IO.Compression.ZipFile.dll
----------------------------------------
System.IO.Compression
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.IO.Compression.dll
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    程序集版本:6.0.0.0
    Win32 版本:6.0.2523.51912
    代码库:file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Collections.Immutable.dll
----------------------------------------

************** JIT 调试 **************

**Comment by JRustyHaner** [comment]
@ljt2623 that error means that there are no files in your input folder

**Comment by ljt2623** [comment]
@JRustyHaner sorry to bother you again and again. error still occurs. i have reinstalled everything and changes corpus,didn't work.

> Input folder: C:\Users\j\Desktop\aigc\in
Output folder: 
Output folder: C:\Users\j\Desktop\aigc\out
Initializing CohMetrix...
Starting: BRJA7.txt Thread: 12
Reading: C:\Users\j\Desktop\aigc\in\BRJA7.txt Thread: 12
Started: BRJA7.txt Thread: 12
ERROR: -Popularte text- SentenceParserBridge
   at SentenceParserBridge.SPB.Run(String command, String args) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\SentenceParserBridge\SentenceParserBridge.cs:line 29
   at MPCharniak.Charniak.start() in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCharniak\Charniak.cs:line 96
   at MPCharniak.Charniak.parse(String sentence) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCharniak\Charniak.cs:line 137
   at MPCharniak.Charniak.parse2(String[] sentences) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCharniak\Charniak.cs:line 157
   at MPCharniak.MPParser.parse(String[] sentences) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCharniak\MPParser.cs:line 46
   at MPCohMetrix.CohMetrix.GetTextRep(String text) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\CohMetrix.cs:line 1138
   at MPCohMetrix.CohMetrix.AnalyzeTextForWeb(String text) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\CohMetrix.cs:line 188

**Comment by JRustyHaner** [comment]
@JRustyHaner could you email BRJA7.txt to me at jrhaner@memphis.edu?

**Comment by seventeen-14** [comment]
Sorry, I have the same problem.
Welcome to CohMetrix Core 1.0  (Build 3)
Please select input and output folder and press analyze to start processing. Threads (amount of files processed at the same time) can be set below to speed up processing.
Number of threads available: 24
Warning: using many threads might slow down your computer. Coh-Metrix is set to use 1 threads.
Input folder: D:\Desktop\dissertation\test
Output folder: D:\Desktop\dissertation\results
Initializing CohMetrix...
**Starting: THE CHINESE WRITING SYSTEM .txt Thread: 12
Reading: D:\Desktop\dissertation\test\THE CHINESE WRITING SYSTEM .txt Thread: 12
Started: THE CHINESE WRITING SYSTEM .txt Thread: 12
ERROR: -Popularte text- SentenceParserBridge**
   at SentenceParserBridge.SPB.Run(String command, String args) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\SentenceParserBridge\SentenceParserBridge.cs:line 29
   at MPCharniak.Charniak.start() in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCharniak\Charniak.cs:line 96
   at MPCharniak.Charniak.parse(String sentence) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCharniak\Charniak.cs:line 137
   at MPCharniak.Charniak.parse2(String[] sentences) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCharniak\Charniak.cs:line 157
   at MPCharniak.MPParser.parse(String[] sentences) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCharniak\MPParser.cs:line 46
   at MPCohMetrix.CohMetrix.GetTextRep(String text) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\CohMetrix.cs:line 1138
   at MPCohMetrix.CohMetrix.AnalyzeTextForWeb(String text) in C:\Users\Rusty\Desktop\workspace\Cohmetrix3_0\cohmetrix3\CohMetrix3\MPCohMetrix\CohMetrix.cs:line 188

**Comment by JRustyHaner** [comment]
@seventeen-14  Please email me THE CHINESE WRITING SYSTEM .txt at jrhaner@memphis.edu

**Comment by ljt2623** [comment]
@JRustyHaner email sent

**Comment by JRustyHaner** [comment]
@ljt2623 The installer is missing a file.

 Please stand by for a new installer version.

**Comment by ljt2623** [comment]
@JRustyHaner good to know that. hope the bug can be fixed soon.

**Comment by JRustyHaner** [comment]
@ljt2623 @seventeen-14 please uninstall and download the new version. The licenses should be the same.
