### ISSUE TITLE
license key request

### ISSUE THREAD

**Issue by Yxc13** [memphis-iis/cohmetrix-issues#29]
Issue Example:

Name: Xuechun Yang

Email: 1844945774@qq.com

Institution: Southwest University of Foreign Languages

Key: 26339123

Description of Your Research: In order to test whether the teaching mode of "reading to promote writing" based on discourse analysis has an impact on the use of cohesive devices in students' continuous writing, I need to use Coh-Mertix 3.0 to analyze the contents of pre-test, mid-test and post-test essays and measure cohesive devices in texts

**Comment by JRustyHaner** [comment]
@Yxc13 That is not a valid license key, please follow the directions and try again.

**Comment by Yxc13** [comment]
@JRustyHaner How to get license key？

**Comment by JRustyHaner** [comment]
@Yxc13 closing this, since another issue was opened for a key.
