### ISSUE TITLE
license key request

### ISSUE THREAD

**Issue by Yxc13** [memphis-iis/cohmetrix-issues#30]
Issue Example:

Name: Xuechun Yang

Email: 1844945774@qq.com

Institution: Southwest University of Foreign Languages

Key: 679 (secret) Build 4

Description of Your Research: In order to test whether the teaching mode of "reading to promote writing" based on discourse analysis has an impact on the use of cohesive devices in students' continuous writing, I need to use Coh-Mertix 3.0 to analyze the contents of pre-test, mid-test and post-test essays and measure cohesive devices in texts

**Comment by JRustyHaner** [comment]
@Yxc13 sent you an email
