### ISSUE TITLE
Understanding writing styles of scientific papers in the IS-LS domain: Evidence from abstracts over the past three decades

### ISSUE THREAD

**Issue by 13100MA** [memphis-iis/cohmetrix-issues#31]
2. Literature review
2.1. Academic writing styles
A scientific paper is a kind of text of a particular genre with a relatively unique academic writing style. Researchers have investigated these styles for decades and pointed out that academic writing is more structurally elaborated (with longer sentences, longer
T-units, and greater use of subordinate clauses) (Brown & Yule, 1983; Chafe, 1982; Kroll, 1977) and explicit (Biber & Gray, 2010).
Considering scientific papers are the manifestation of communication among researchers without a shared situational context, the
writing styles were claimed to be decontextualized and autonomous, and the logical relations should be overtly encoded (DeVito, 1966;
Johns, 1997; Kay, 1977).
However, Bennett (2009) also noted that one of the most critical concerns for academic writing style is “economy or conciseness,”
which could lead to another explanation. Biber and Gray (2010) conducted a long-term study based on a large-scale corpus and
pointed out that academic writing styles were becoming more implicit and forming into a more “compressed and nominalized” style.
Biber and Gray (2010) further explained that with the deepening of the research and the increase in the amount of information in
the paper, a more concise writing method was needed to transmit innovative knowledge more efficiently. This method could assist
researchers with specific background knowledge in quickly obtaining a large amount of information.
Meanwhile, the factors that contributed to the development of academic writing styles could be diverse, including the rise of
experimental research, the development of numerous sub-disciplines, the change in technology, and the association with the “information explosion” (Atkinson, 1999; Gross, Harmon & Reidy, 2002). From these perspectives, understanding the writing styles of a
research domain proposed a path to illustrate the changing of discipline construction, the variations of subfields, journal preference,
and scientific impact.
2.2. Writing styles with computational linguistics of scientific papers
Scientific papers manifest scientific knowledge with specific rhetorical structures and writing styles (Lu et al., 2019b; Snow, 2010).
Research paradigms, fields, and methods may influence particular ways of writing, whereas writing styles might influence their
scientific impact. Therefore, a quantitative analysis of scientific writing is essential. Table 1 summarizes previous empirical studies
on research articles and the linguistic features used.
Studies aimed at revealing the writing styles of research articles have mainly used multidimensional analysis. Linguistic features
include both lexical and syntactic features. For lexical indicators, vocabulary-based discourse units (Biber et al., 2002), emphasizers
(Diani, 2008), and pronouns (Harwood, 2005; Hyland, 2001a) were used. For syntactic indicators, complexity was calculated using

**Comment by JRustyHaner** [comment]
@13100MA Please send a license key by following the instructions on the readme page at https://github.com/memphis-iis/cohmetrix-issues
