### ISSUE TITLE
Coh-Metrix License Issue Request

### ISSUE THREAD

**Issue by mart221** [memphis-iis/cohmetrix-issues#33]
Name: Martin Walczak

Email: mwalczak@cougarnet.uh.edu

Insitution: University of Houston

Secret key: 695

Description of your research: The effects of domain-general and domain-specific item features on item difficulty of STEM assessments in English language learners and non-English language learners

**Comment by JRustyHaner** [comment]
@mart221 Sent you an email with a key. Thanks
