### ISSUE TITLE
Ashon Song applying for the access to Cohmetrix

### ISSUE THREAD

**Issue by ashonshaw** [memphis-iis/cohmetrix-issues#41]
Name: Ashon Song

Email: ashonshaw@gmail.com

Insitution: Beijing Foregn Stuides University

Secret key: 686 (secret) Build 4

Description of your research: a comparative study of the translation texts by different agents.

**Comment by JRustyHaner** [comment]
@ashonshaw A license has been sent to you. Thanks!
