### ISSUE TITLE
Request for Coh-Metrix

### ISSUE THREAD

**Issue by YunyeYu** [memphis-iis/cohmetrix-issues#45]
Name: Yunye Yu, Ph.D.

Email: yunye.yu@seu.edu.cn

Insitution: Southeast University (China)

Secret key: 688 (secret) Build 4

Description of your research: I need to compare and analyze two writing groups: human writers and onw human-AI collaborative writing. I would like to analyze the linguistic differences in the writing.

**Comment by JRustyHaner** [comment]
@YunyeYu a license has been sent to your email. Thanks!

**Comment by YunyeYu** [comment]
> @YunyeYu a license has been sent to your email. Thanks!

Thank you so much!
