### ISSUE TITLE
License request：713 (secret) Build 3

### ISSUE THREAD

**Issue by geostu1014** [memphis-iis/cohmetrix-issues#47]
Name: Guishuai Feng
Email: fgs@my.swjtu.edu.cn
Institution: Southwest Jiaotong University

**Comment by JRustyHaner** [comment]
@geostu1014 Build 3 is not a current build, we do not release keys for old builds Please download the most recent build.

**Comment by JRustyHaner** [comment]
@geostu1014 you should uninstall and delete the CohMetrixCore install directory before installing the newest version
