### ISSUE TITLE
license key

### ISSUE THREAD

**Issue by hanghanglee** [memphis-iis/cohmetrix-issues#49]
Hello, my name is Hang Li. My e-mail address is hanghangli@zju.edu.cn. I am currently working at Zhejiang University, P. R. China. I am trying to use Cohmetrix, and was told to provide the information above in order to get the license key. 

Hang Li

**Comment by JRustyHaner** [comment]
@hanghanglee I need the secret key from the application. It is provided to you upon startup.

**Comment by JRustyHaner** [comment]
@hanghanglee This thread is being closed. The last comment was not replied to over the course of a week.
