### ISSUE TITLE
Request to get registered

### ISSUE THREAD

**Issue by Nannii1** [memphis-iis/cohmetrix-issues#51]
Hi. It would be nice if you send me the license key. Below are the information that you asked. Thank you.

Name: Nayeon Kim

Email: monmamia@naver.com

Insitution: Kyunghee University

Secret key: 719 (secret) Build 4

Description of your research: I want to analyze high school students' utterances. So I made some transcripts from the audio that students recorded, and I'm trying to analyze those transcripts.

**Comment by JRustyHaner** [comment]
@Nannii1 A key has been emailed to you. Thanks!
