### ISSUE TITLE
License key

### ISSUE THREAD

**Issue by ricardoRadaelli** [memphis-iis/cohmetrix-issues#52]
Name: Ricardo Radaelli Meira

Email: ricardoradaelli@gmail.com

Insitution: Universidade Federal do Rio Grande do Sul (UFRGS) - Brasil

Secret key: 692 (secret) Build 4

Description of your research

I am researching applications of textual metrics in Brazilian Portuguese and I want to compare these metrics with those generated in texts written in English.

**Comment by JRustyHaner** [comment]
@ricardoRadaelli A license has been emailed to you. Thanks!
