### ISSUE TITLE
Registration License Information

### ISSUE THREAD

**Issue by LEID996** [memphis-iis/cohmetrix-issues#60]
Name：lei Dong
Email：1225549500@qq.com
Secret key: 612 (secret) Build 4
Institution：Xi`an University Of Posts & Telecommunications
Description of your research: This study will establish a corpus of master's and doctoral theses, using a second language syntactic complexity analyzer (L2SCA), lexical complexity analyzer (LCA), and discourse coherence analyzer (Coh Metrix) to compare the readability, lexical richness, and syntactic complexity of engineering and humanities graduation thesis abstracts.

**Comment by JRustyHaner** [comment]
@LEID996 a license has been sent to your email!
