### ISSUE TITLE
register

### ISSUE THREAD

**Issue by mkclairhong** [memphis-iis/cohmetrix-issues#62]
Name: Min Kyung Hong

Email: clair.hong@vanderbilt.edu

Institution: Vanderbilt University

Secret key: need one 

Description of your research: free recall analysis

**Comment by JRustyHaner** [comment]
@mkclairhong You must provide the secret key by running the software. Please read the instructions again.

**Comment by JRustyHaner** [comment]
@mkclairhong

**Comment by mkclairhong** [comment]
My apologies. The secret key is "691 (secret) Build 4"

**Comment by JRustyHaner** [comment]
@mkclairhong A key has been sent to your email!
