### ISSUE TITLE
Licensing Key for CohMetrix

### ISSUE THREAD

**Issue by NadjaMT** [memphis-iis/cohmetrix-issues#63]
Name: Nadja Taha

Email: n.m.taha@student.utwente.nl

Insitution: University of Twente, Netherlands

Secret key: 736 (secret) Build 4

Description of your research: The aim of the project is to determine in what ways and to what extent the language in newspaper articles has changed over time. In particular, to investigate whether there have been any changes since the rise of the internet (mid-1990s) and the rise of smartphones (second decade of the 21st century). It is expected that a period of fifty years is long enough to reveal trend changes in language use.

**Comment by NadjaMT** [comment]
I am trying to use the software on both my devices. The secret key for the other device is: 672 (secret) Build 4
In case I need multiiple keys for that, I would appreciate having both licensed. :)

**Comment by JRustyHaner** [comment]
@NadjaMT license keys have been emailed to you. Thanks!
