### ISSUE TITLE
license key request

### ISSUE THREAD

**Issue by Jenny-Qiu-941** [memphis-iis/cohmetrix-issues#69]
Name: Jenny Qiu

Email: 0223100214@shisu.edu.cn

Institution: Shanghai International Studies University

Secret key: 710

Description of your research: Translation Studies, Corpus Linguistics

Hi dear developers, could you please provide me with a license key? Thank you a lot!

**Comment by JRustyHaner** [comment]
@Jenny-Qiu-941 A license has been emailed to you. Thanks!
