### ISSUE TITLE
CohMetrixCoreCLI for mac os error

### ISSUE THREAD

**Issue by mkclairhong** [memphis-iis/cohmetrix-issues#70]
Hi, I'm getting this error - could you please look into the MacOS version? Thank you!

```
Coh-Metrix Core CLI Build 3
University of Memphis: Institute for Intelligent Systems
Error Checking for Updates.
This is not the latest version of Coh-Metrix Core. Please update to the latest version.
Unhandled exception. System.IO.IOException: Read-only file system : '/CohMetrixCore'
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at CohMetrixCoreCLI.Program.Main(String[] args) in /Users/jrhaner/Desktop/workspace/CohMetrixCore/CohMetrixCoreCLI/Program.cs:line 79
zsh: abort      

```

**Comment by JRustyHaner** [comment]
@mkclairhong please check that ~/.local/share/CohMetrixCore/data exists please.

**Comment by mkclairhong** [comment]
Thank you! I confirmed it did not but making that directory seemed to have solved the problem :)!

**Comment by JRustyHaner** [comment]
The data folder should have several subfolders. If it doesn't, you'll get another error.

@mkclairhong

**Comment by mkclairhong** [comment]
Oh I see. Would you please the mac os file on the repo to contain the correct subfolders in `~/.local/share/CohMetrixCore/data` ? Or is that something I could fetch from other versions?

**Comment by JRustyHaner** [comment]
@mkclairhong if you can't give the app write access, the data zip file is available here: http://141.225.61.35/data.zip

**Comment by mkclairhong** [comment]
Thank you!

**Comment by JRustyHaner** [comment]
Welcome! Closing for now
