### ISSUE TITLE
license key request

### ISSUE THREAD

**Issue by nerserhub** [memphis-iis/cohmetrix-issues#72]
Name: nerserhub

Email: 837313671@qq.com

Institution: zhejaing University

Secret key: 0 (secret) Build 4

Description of your research: The picture-speaking task corpus of Alzheimer's disease patients and healthy control group was analyzed

**Comment by JRustyHaner** [comment]
@nerserhub Is the output of the secret key 0? That's pretty rare, its normally a 3 digit number. Please send me a screenshot.

**Comment by nerserhub** [comment]
@JRustyHaner Sorry. I don't know why I drag the picture to the chat box but it doesn't show, I haven't used github very long. Open the software it prompts "Please update to the latest version of CohMetrix Core", but I didn't notice it yesterday, sorry. Yesterday I downloaded from a new website(https://www.linguisticanalysistools.org/), and it can work. Sorry to bother you.

**Comment by JRustyHaner** [comment]
@nerserhub ho problem, I'll close this issue.
