### ISSUE TITLE
license key request for Mac OS

### ISSUE THREAD

**Issue by mkclairhong** [memphis-iis/cohmetrix-issues#73]
Name: Clair Hong

Email: mkclairhong@gmail.com

Institution: Vanderbilt University

Secret key:730 (secret) Build 3

Description of your research: reading research - free recall analysis

**Comment by JRustyHaner** [comment]
You may now use our self service portal here: http://cohmetrix-new.memphis.edu/ @mkclairhong

**Comment by mkclairhong** [comment]
This is amazing- thank you so much!
