### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by terezakubankova** [memphis-iis/cohmetrix-issues#76]
Name: Tereza Kubanova

Email: tereza.kubankova@gmail.com

Insitution: UJEP 

Secret key: 690

Description of your research: I am researching a corpus of ChatGPT and its ability to produce texts suitable for teaching reading comprehension. I'm interested in how specifically can generative AI be used for the production of texts and other teaching implications in teaching reading comprehension.  The thesis will assess the suitability of using AI-generated teaching aids and analyze texts produced by ChatGPT on levels A1-B2 according to Common European Framework of Reference for teaching languages.

**Comment by mkclairhong** [comment]
they now have a self service portal for generating your API key! http://cohmetrix-new.memphis.edu/

**Comment by JRustyHaner** [comment]
@mkclairhong it doesn't work for the Windows version, but that will come very soon.
