### ISSUE TITLE
license key not valid error 

### ISSUE THREAD

**Issue by mkclairhong** [memphis-iis/cohmetrix-issues#78]
Hi, 

I'm getting the following  "license key is not valid" error and I've confirmed that I have all the requirements installed and tried multiple times with new API keys. 

```
Getting License Key from API
Trying License Server:  http://cohmetrix-new.memphis.edu/api/getDesktopKey
License is not valid.
Press any key to exit.
```

Could you please look into this issue?

**Comment by JRustyHaner** [comment]
@mkclairhong are you pasting the api key in from the website? If so, MacOS tends to add an extra space to the end of it. Try removing that extra space.

**Comment by mkclairhong** [comment]
Unfortunately I'm seeing the same error even after ensuring that there are no extra spaces

**Comment by JRustyHaner** [comment]
Inside of the installation folder is there a license.txt file?

**Comment by mkclairhong** [comment]
Yes! 
[license.txt](https://github.com/memphis-iis/cohmetrix-issues/files/14513992/license.txt)

**Comment by JRustyHaner** [comment]
Try deleting it. I might have left my test license in there.

**Comment by mkclairhong** [comment]
I tried again but the same error is shown again after creating a new license.txt ... Thanks for looking into this!!
[license.txt](https://github.com/memphis-iis/cohmetrix-issues/files/14514112/license.txt)

**Comment by JRustyHaner** [comment]
When you run the application, does it give you the secret number?

**Comment by mkclairhong** [comment]
I can get the secret number by entering an invalid username like this:
```
Email: 
mkclairhong
API Key: 
8f7KTnFZHhfdqGSf7eyweS
Getting License Key from API
Trying License Server:  http://cohmetrix-new.memphis.edu/api/getDesktopKey
License key generation failed. Please check your username and API key. Error: error: user not found
Please enter your license key. You may create an issue on the GitHub repository if you are having trouble generating a key.
Please reference your secret: 730
Please enter your license key: 


```

**Comment by JRustyHaner** [comment]
I've opened up the web tool. I'll generate you a license as soon as I can

**Comment by JRustyHaner** [comment]
@mkclairhong 
License Info:
License Key: 621847
License is valid

**Comment by mkclairhong** [comment]
thank you!
