### ISSUE TITLE
Could not download data from "http://cohmetrix.memphis.edu/api/downloadData"

### ISSUE THREAD

**Issue by fdiskdc** [memphis-iis/cohmetrix-issues#79]
Name:fdisk dc
Email: chaoteng987@outlook.com
Institution: NNNU university
Secret Key:FPrN7Lvj7Hs2CZMKxiST2X
Description of your research:Language model

I have tried to execute "CohMetrixCoreCLI.exe" on Windows and Ubuntu. However, the output of the terminal looks like this:
<img width="856" alt="image" src="https://github.com/memphis-iis/cohmetrix-issues/assets/60283551/bd90bbe7-a2f2-4ee2-aec9-94ab8b7732c6">
I believe that there are no issues with my internet connection.

**Comment by JRustyHaner** [comment]
please check if http://cohmetrix-new.memphis.edu/api/downloadData works in your web browser.

**Comment by fdiskdc** [comment]
I had received respound from "http://cohmetrix-new.memphis.edu/api/downloadData" in my web browser and downloaded the "downloadData.zip" successfully.
<img width="95" alt="image" src="https://github.com/memphis-iis/cohmetrix-issues/assets/60283551/400b061f-6af0-4882-8d58-1db06f67236d">

However, it still don't work in "CohMetrixCoreCLI"

**Comment by JRustyHaner** [comment]
You must put it into C:\Users\AppData\Local\CohMetrixCore\data. However, if you can access that link, I would ask that you restart cohmetrix, log in to the form, and allow the software to download it.

@fdiskdc I would also implore you to fix your profile. We need a different answer for your research goals that is not just a copy/paste of the prompt, otherwise we will have to revoke your API key.

**Comment by fdiskdc** [comment]
I am sorry, I had update my research goal on the website.
Also, I put "downloadData.zip" into "C:\Users\AppData\Local\CohMetrixCore\data"
But , command line still have an issue that "License key generation failed" and looks like this
<img width="859" alt="image" src="https://github.com/memphis-iis/cohmetrix-issues/assets/60283551/02d4ea5f-8d3a-413e-a6a6-93effac16e0c">
Terminal  are closed after I push the Enter key whever I input.

**Comment by JRustyHaner** [comment]
please try again. There was an error on the server that needed addressed.
