### ISSUE TITLE
License is not valid. and "Your License Key for secret 682 is 847093."

### ISSUE THREAD

**Issue by fdiskdc** [memphis-iis/cohmetrix-issues#80]
Name:fdisk dc
Email: [chaoteng987@outlook.com](mailto:chaoteng987@outlook.com)
Institution: NNNU university
Secret Key:FPrN7Lvj7Hs2CZMKxiST2X
Description of your research:Language model

I am trying to start up "CohMetrixCore.exe". However, it shows that I have an invalid key. But I have registered my information on the website.
And that program shows like this:
<img width="593" alt="image" src="https://github.com/memphis-iis/cohmetrix-issues/assets/60283551/13395f54-7189-46fd-b276-8ff1450758d4">

I sincerely appreciate your help.

**Comment by JRustyHaner** [comment]
Please open the install directory and find license.txt and try replacing it's contents with 21847.

**Comment by fdiskdc** [comment]
This morning when I wake up, I founded that log has been changed and my API key didn't work any more.
The log file shows like this:
<img width="597" alt="image" src="https://github.com/memphis-iis/cohmetrix-issues/assets/60283551/df8396c2-6f2d-402a-bf93-f489124ff5c8">
I had generated a new API key but still don't work.
Also, I add a "license.txt" File with content "21847" to my install directory, CohMetrixCore still output "License key generation failed. Please check your username and API Key. Error: " But my email and API key are correct.
