### ISSUE TITLE
License key generation failed

### ISSUE THREAD

**Issue by AlteraFox** [memphis-iis/cohmetrix-issues#82]
Hi,

Name: GU Yuxuan

Email: foxgyx@gmail.com

Insitution: Southwest University of Political Science and Law

Secret key: 

Description of your research: Using the tool to research MT legal translation in comparison with human translations

Problem: I can't generate my license key with my username and API Key; the software keeps telling me to try again. I checked my internect connection and my personal info, but I couldn't find what went wrong
![image](https://github.com/memphis-iis/cohmetrix-issues/assets/165973162/efc36bc2-d76b-4ecc-abb9-745467fc0809)

**Comment by JRustyHaner** [comment]
@AlteraFox Thanks for reaching out. Please open the installation folder and check the license.txt file. It should read 84709. If it doesn't, please change it and restart. We will look into the issue on the generation of keys.

**Comment by AlteraFox** [comment]
Thanks for replying, but I can't find the license.txt file in the installation folder, do I need to re-install the software?
![image](https://github.com/memphis-iis/cohmetrix-issues/assets/165973162/07fc047f-d445-4fb2-a746-0876b47360cd)

**Comment by JRustyHaner** [comment]
@JRustyHaner The server has been fixed. Please try again using the prompt in the software.

**Comment by AlteraFox** [comment]
Thanks a lot!
