### ISSUE TITLE
new version of cohmetrix vs. older version output

### ISSUE THREAD

**Issue by mkclairhong** [memphis-iis/cohmetrix-issues#85]
Hi, 

I've noticed that some values, such as word concreteness, differ between the older and newer versions. Is that to be expected?

**Comment by JRustyHaner** [comment]
@mkclairhong which versions are you comparing the output from?

**Comment by mkclairhong** [comment]
I am comparing an output from 2021 to the newest release of cohmetrix

**Comment by JRustyHaner** [comment]
@mkclairhong and what seems to be different?

**Comment by mkclairhong** [comment]
The values for word concreteness. Could you please tell us where these values are pulled from?

**Comment by JRustyHaner** [comment]
@mkclairhong could you compare it against the web tool?

**Comment by JRustyHaner** [comment]
@mkclairhong This is being closed due to inactivity
