### ISSUE TITLE
MacOs command not found CohMetrixCoreCLI

### ISSUE THREAD

**Issue by cideri** [memphis-iis/cohmetrix-issues#86]
Hi, followed the instructions here: http://cohmetrix-new.memphis.edu/download. I already installed .NET Core 7 SDK and ASP.NET Core 7. I'm stuck at step 3. Copy pasted the terminal output. 

```
CamillAIRos:cohmetrixcoregui-2.0a-macos cideri$ CohMetrixCoreCLI
-bash: CohMetrixCoreCLI: command not found
CamillAIRos:cohmetrixcoregui-2.0a-macos cideri$ 
```

**Comment by cideri** [comment]
Found it sorry

**Comment by JRustyHaner** [comment]
@cideri No worries, please let us know if there are any further issues
