### ISSUE TITLE
Error Could not download data from any URL

### ISSUE THREAD

**Issue by cideri** [memphis-iis/cohmetrix-issues#87]
Hello, trying to use CohMetrix on MacOs and I'm still somehow stuck at step 3.
When I run CohMetrixCoreCLI from the terminal I get this error copy pasted below. 
I have already deleted the folder mentioned in code page (~/.local/share/CohMetrixCore) so I don't understand why it says that my version is not the latest. 
Thank you for your help.

This` is not the latest version of Coh-Metrix Core. Please update to the latest version.
Downloading model data...
Data downloaded from  http://cohmetrix-new.memphis.edu/api/downloadData
Could not download data from http://cohmetrix.memphis.edu/api/downloadData . Trying next URL.
Could not download data from http://localhost:3000/api/downloadData . Trying next URL.
Unhandled exception. System.Exception: Could not download data from any URL. Please check your internet connection and try again.
   at CohMetrixCoreCLI.Program.<>c__DisplayClass15_0.<<Main>b__1>d.MoveNext() in /Users/jrhaner/Desktop/workspace/CohMetrixCore/CohMetrixCoreCLI/Program.cs:line 99
--- End of stack trace from previous location ---
   at CohMetrixCoreCLI.Program.Main(String[] args) in /Users/jrhaner/Desktop/workspace/CohMetrixCore/CohMetrixCoreCLI/Program.cs:line 82
Abort trap: 6
logout

**Comment by JRustyHaner** [comment]
@cideri Which operating system are you using?

**Comment by cideri** [comment]
Hi @JRustyHaner 

I'm using MacOs Ventura (as well as trying to run it on another pc with Windows and following issue #83 I actually manage to get the Desktop Tool running there, though I'm having some issues reading the output files). 
I've downloaded the data folder but I got lost at trying to see if it's in the right place/put it there.

Also, today the online tool is working - don't know why but it used to get stuck at processing so I'm doing as much as I can with that for now. 

Thank you!

**Comment by JRustyHaner** [comment]
@cideri  Of course. Usually the data files are stored at /Users/USERNAME/.local/share/cohmetrixcore for MacOS.  There is a new dotnet 8 version of cohmetrix available that is a gui version that you might make use of.  

If there's anything we can help with let us know
