### ISSUE TITLE
Error: No connection could be made because the target machine actively refused it 127.0.0.1:8666

### ISSUE THREAD

**Issue by Shirley0103S** [memphis-iis/cohmetrix-issues#9]
It was still working a few days ago. But these days when I use it, it always has this kind of error, is it my problem or the web tool is down? 
<img width="1440" alt="截屏2023-11-29 下午10 30 33" src="https://github.com/memphis-iis/cohmetrix-issues/assets/152389809/2795d031-19e7-4e6b-92be-177e74d38b39">

**Comment by JRustyHaner** [comment]
@Shirley0103S thank you fore reporting this. Cohmetrix has been restarted.
