### ISSUE TITLE
Use of CohmetrixCore for research purposes

### ISSUE THREAD

**Issue by DeaJesp** [memphis-iis/cohmetrix-issues#92]
Hi,

I am looking forward to using CohmetrixCore in a desktop version. :) 
I hope this is the procedure to follow (cf https://github.com/mkclairhong/cohmetrix/blob/main/Readme.md). Will this issue remain accessible for all users?

Registration info:

Name: Dea Jespersen
Email: deajespersen@hum.ku.dk
Institution: University of Copenhagen
Secret key: 653 (secret) Build 4
Description of your research: Comparing L2 digital writing processes and products with and without internet access

**Comment by JRustyHaner** [comment]
@DeaJesp That repository you have received your version from is an unauthorized distributor of Cohmetrix. Cohmetrix is available on a self service portal at http://cohmetrix-new.memphis.edu. Please follow the registration and instructions there.

**Comment by DeaJesp** [comment]
Oh. Thank you. The version has now been deleted.
I need help signing up on http://cohmetrix-new.memphis.edu/. I get the message that the connection is not secure.
