### ISSUE TITLE
cohmetrix description page

### ISSUE THREAD

**Issue by mkclairhong** [memphis-iis/cohmetrix-issues#94]
Hi,

On the old Coh-Metrix website, there used to be a page detailing the Coh-Metrix measures. Is there a way to retrieve that page, or could you please direct me to where it may have moved?

**Comment by JRustyHaner** [comment]
@mkclairhong we're working on getting that to you. The old cohmetrix server was taken down due to a server vulnerability.

**Comment by mkclairhong** [comment]
Hi! Has there been any updates on this issue by chance? Thanks!

**Comment by JRustyHaner** [comment]
@mkclairhong yep, this has been added. A user guide is available in the main menu.
