### ISSUE TITLE
Linux CLI: Download Data not working properly

### ISSUE THREAD

**Issue by contemmcm** [memphis-iis/cohmetrix-issues#96]
After running CohMetrix for the first time, the app also looks into http://localhost:3000, making the download process to fail. I believe there is a bug in the download loop. This does not seems to happen on the gtk version, only on the CLI version.

**Comment by JRustyHaner** [comment]
@contemmcm perhaps. Localhost is the first place it looks before looking for our distribution servers. We have that in there for testing purposes. If you run the GTK edition, the CLI version will work as well, since they store the data files in the same path. We will look into this.

**Comment by DeaJesp** [comment]
Hi,
I also experience a problem with CohMetrix, trying to fetch data from http://localhost:3000. I'm running the Windows version CohMetrix. The problem seems to occur both with the CLI and the Desktop version.

Here is a trace of the Error I get when trying to run the CLI:
```
Coh-Metrix Core CLI Build 6
University of Memphis: Institute for Intelligent Systems
Downloading model data...
Data downloaded from  http://cohmetrix-new.memphis.edu/api/downloadData
Data downloaded from http://cohmetrix.memphis.edu/api/downloadData
Could not download data from http://localhost:3000/api/downloadData . Trying next URL.
Unhandled exception. System.Exception: Could not download data from any URL. Please check your internet connection and try again.
   at CohMetrixCoreCLI.Program.<>c__DisplayClass16_0.<<Main>b__1>d.MoveNext() in C:\Users\rusty\OneDrive\Desktop\Local Workspace\cohmetrixcore\CohMetrixCore\CohMetrixCoreCLI\Program.cs:line 174
--- End of stack trace from previous location ---
   at CohMetrixCoreCLI.Program.Main(String[] args) in C:\Users\rusty\OneDrive\Desktop\Local Workspace\cohmetrixcore\CohMetrixCore\CohMetrixCoreCLI\Program.cs:line 157
```

**Comment by JRustyHaner** [comment]
@contemmcm This issue will be closed because someone has not replied to it in a few months.
