### ISSUE TITLE
The license key of Coh-Metrix

### ISSUE THREAD

**Issue by Eloiseyvvv** [memphis-iis/cohmetrix-issues#99]
Name: Wei Zhong
Email: zhongwei0208@gmail.com
Institution: Shanghai International Studies University

Please email me about the license key of Coh-Metrix. Thank you very much:)

**Comment by JRustyHaner** [comment]
We no longer use that system to give keys. Please see the documentation. The keys are now available at cohmetrix.memphis.edu
